### ISSUE TITLE
[FEAT] Monitoring Elrond Nodes with Telegraf + InfluxDB + Grafana.

### ISSUE THREAD

**Issue by ubun3t** [multiversx/mx-chain-go#1854]
Monitor your nodes is very important for reach high rating and network performance. 

In this guide we are going to see how to install and configure Grafana + Influxdb + Telegraf to monitor a Elrond node based on Ubuntu 18.04.

https://github.com/ubun3t/telegraf-erd-monitor

This is a summary video:

[![Watch the video](https://img.youtube.com/vi/5Yxq0GfpQU8/maxresdefault.jpg)](https://www.youtube.com/watch?v=5Yxq0GfpQU8)

**Comment by ubun3t** [comment]
Hi Lulian, I have not been able to give proper attention to this project
because of limited time availability and the preference of the community
towards more advanced solutions like Zabbix, etc.

Regards,

**Comment by iulianpascalau** [comment]
Thanks, will close this. And btw, my name is not Lulian.
