### ISSUE TITLE
[Proposal] make the new upgrade have cleanup that can auto removing the other existing go or golang coz it's make the installation stop on Downloading Go Module so any upgrade will corrupt

### ISSUE THREAD

**Issue by scraido** [multiversx/mx-chain-go#1857]
For the new version after v.124. I need this new feature because before i knowing the trouble it really stress me out how to fix it and the existing feature set is not enough, it's couldn't completely remove the existing **GO** that set by server or other network (before). first you just need to remove go directory in /usr/local/ then change the content in $HOME/.profile maybe do a replacing, thanks for your support & hard work for this whole time it's really awesome guys, thank you

**Comment by iulianpascalau** [comment]
I think this is fixed in the last version of the unified scripts https://github.com/multiversx/mx-chain-scripts. Closing this PR for now, thanks for submitting this.
