### ISSUE TITLE
[FEAT] Update and improve Docker environment setup

### ISSUE THREAD

**Issue by tebayoso** [multiversx/mx-chain-go#2708]
This is not a feature but a way to improve the development setup. 

The docker compose is outdated, over 2 years since it was started and some of the repos created. Some of the features are still there but unmaintained.

Expending time on fixing this will ensure e2e testing can be made against any new stable release and will also allow us to run nodes in parallel.

**Comment by iulianpascalau** [comment]
Fixed, we now have 3 docker images, each configured for the 3 public chains. References:
https://github.com/multiversx/mx-chain-mainnet-config/blob/master/docker/Dockerfile
https://github.com/multiversx/mx-chain-testnet-config/blob/master/docker/Dockerfile
https://github.com/multiversx/mx-chain-devnet-config/blob/main/docker/Dockerfile

Will close this for now, thanks for opening this issue.
