### ISSUE TITLE
[FEAT] Raise a warning when a block is not accepted

### ISSUE THREAD

**Issue by SaltwaterC** [multiversx/mx-chain-go#3096]
I've been trying to figure out the reason why some blocks are not accepted i.e there's a mismatch between validator signed blocks and blocks accepted. `*:DEBUG` is essentially unreadable and even knowing the rough time a block is not accepted, I couldn't figure it out. If I run the node with `*:INFO` (which is reasonable for a production service as I don't think DEBUG is appropriate for a live service), then no information is printed about the reason a block signature didn't make the cut.

So, my proposal is pretty simple: log something as warning if this happens and a reason. I'm looking for ways to improve the stability of the node I'm running and this is the one thing I can't figure out.

**Comment by iulianpascalau** [comment]
Hello, thanks for opening this issue.
Unfortunately, we won't be able to do this printing for various reasons. Such reasons include the following errors:
bad manual config that will make the node unable to accept or correctly process a block/transactions. Also, any node can output data on the specified p2p channels, we are presuming that the other nodes are faulty if the current node can not obtain the same result by processing internally the provided data. So the problem with detecting such errors is the lack of "a trusted point of reference". This is intended in p2p environments as opposed to centralized client-server setups.
Will close this for now.
