### ISSUE TITLE
[FEAT] Avoid override for external.toml during squad/nodes upgrade

### ISSUE THREAD

**Issue by mihaieremia** [multiversx/mx-chain-go#4303]
We should find a way to not force the override of the external.toml file.

The problem is when you have an Elastic Search attached or the notifier go client configured in this file.

At each upgrade there is a downtime as long as there is not a cluster of squads pointed to the same notifier client to have a backup of events pushed in rabbit
Same happens with the ElasticSearch if there are not more than 1 squad

**Comment by valentin-lup** [comment]
Hey ! 
Great suggestion. We've started work on a fix for the issue !

**Comment by iulianpascalau** [comment]
Since we are approaching the release of the rc/v1.4.0, we can close this at it will be solved by overriding values in prefs.toml. Thanks for the suggestion.
