### ISSUE TITLE
## [Codecov](https://app.codecov.io/gh/multiversx/mx-chain-go/pull/5280?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=multiversx) Report

### ISSUE THREAD

**Issue by histeriabdg** [multiversx/mx-chain-go#5336]
## [Codecov](https://app.codecov.io/gh/multiversx/mx-chain-go/pull/5280?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=multiversx) Report
Patch coverage: **`81.81`**% and project coverage change: **`+0.03`** :tada:
> Comparison is base [(`65caf86`)](https://app.codecov.io/gh/multiversx/mx-chain-go/commit/65caf865639787c2320246b979a61446b29e1daa?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=multiversx) 77.56% compared to head [(`0fa1372`)](https://app.codecov.io/gh/multiversx/mx-chain-go/pull/5280?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=multiversx) 77.60%.

> :exclamation: Current head 0fa1372 differs from pull request most recent head d113fb7. Consider uploading reports for the commit d113fb7 to get more accurate results

<details><summary>Additional details and impacted files</summary>

```diff
@@              Coverage Diff              @@
##           rc/v1.5.0    #5280      +/-   ##
=============================================
+ Coverage      77.56%   77.60%   +0.03%     
=============================================
  Files            654      654              
  Lines          86000    86015      +15     
=============================================
+ Hits           66705    66751      +46     
+ Misses         14090    14059      -31     
  Partials        5205     5205              
```

| [Impacted Files](https://app.codecov.io/gh/multiversx/mx-chain-go/pull/5280?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=multiversx) | Coverage Δ | |
|---|---|---|
| [common/enablers/enableEpochsHandler.go](https://app.codecov.io/gh/multiversx/mx-chain-go/pull/5280?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=multiversx#diff-Y29tbW9uL2VuYWJsZXJzL2VuYWJsZUVwb2Noc0hhbmRsZXIuZ28=) | `74.10% <33.33%> (-0.90%)` | :arrow_down: |
| [process/transaction/baseProcess.go](https://app.codecov.io/gh/multiversx/mx-chain-go/pull/5280?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=multiversx#diff-cHJvY2Vzcy90cmFuc2FjdGlvbi9iYXNlUHJvY2Vzcy5nbw==) | `82.75% <50.00%> (ø)` | |
| [common/enablers/epochFlags.go](https://app.codecov.io/gh/multiversx/mx-chain-go/pull/5280?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=multiversx#diff-Y29tbW9uL2VuYWJsZXJzL2Vwb2NoRmxhZ3MuZ28=) | `92.19% <100.00%> (+0.08%)` | :arrow_up: |
| [process/transaction/shardProcess.go](https://app.codecov.io/gh/multiversx/mx-chain-go/pull/5280?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=multiversx#diff-cHJvY2Vzcy90cmFuc2FjdGlvbi9zaGFyZFByb2Nlc3MuZ28=) | `72.74% <100.00%> (+0.47%)` | :arrow_up: |

... and [2 files with indirect coverage changes](https://app.codecov.io/gh/multiversx/mx-chain-go/pull/5280/indirect-changes?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=multiversx)

</details>

[:umbrella: View full report in Codecov by Sentry](https://app.codecov.io/gh/multiversx/mx-chain-go/pull/5280?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=multiversx).   
:loudspeaker: Do you have feedback about the report comment? [Let us know in this issue](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=multiversx).

_Originally posted by @codecov[bot] in https://github.com/multiversx/mx-chain-go/issues/5280#issuecomment-1562608779_

**Comment by bogdan-rosianu** [comment]
Not an issue, but simply the output of a Codecov run
