### ISSUE TITLE
[Question]: Exporting transactions from raw DB files

### ISSUE THREAD

**Issue by doudyy** [multiversx/mx-chain-go#5566]
### Question

I'm attempting to export all transactions related to a specific account without involving Elasticsearch, and I'm wondering if it would be possible for me to write a Go program (starting from the mx-chain-go code) to directly read the LevelDB database e.g. `elrond-nodes/node-0/db/1/Epoch_1126/Shard_0/Transactions/000002.ldb`.

Are there any technical issues blocking me from completing such a task?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bogdan-rosianu** [comment]
Hello. 
Yes, you should be able to perform this. 
What to take into consideration: 
- the `Transactions` unit will only contain the user-triggered transactions (so will not include the SCRs, rewards txs and so on). For the rest, you should also parse `UnsignedTransactions`, `RewardTransactions`, and `Receipts`
- You should range over the keys of that database. The key will be the transaction's hash, while the value will be the `gogo protobuf` serialization of the transaction. For go you can use [this](https://github.com/multiversx/mx-chain-core-go/blob/main/data/transaction/transaction.pb.go), for js/ts you can use [this](https://github.com/multiversx/mx-sdk-js-core/tree/main/src/proto) and for java you can use [this](https://github.com/multiversx/mx-sdk-java/blob/925609724c9b4451156060fa8079e03192047156/src/main/java/multiversx/Transaction.java#L103)

**Comment by bogdan-rosianu** [comment]
Hi @doudyy did you have the chance to take a look over my answer? Can we close this issue?

**Comment by doudyy** [comment]
Thank you for your valuable insights for parsing the LevelDB database. However, after a thorough examination, I've come across significant technical intricacies.

Unfortunately, due to the project's intricate nature and the challenges posed by the over-engineered design, coupled with limited resources for quality support from your technical team, I will aim to refrain from any further involvement with the MultiversX project.
