### ISSUE TITLE
[Question]: How can I query the history getTotalCumulatedRewardsForUser 

### ISSUE THREAD

**Issue by sylviahuang123** [multiversx/mx-chain-go#5614]
### Please write the desired question

How can I query the history `getTotalCumulatedRewardsForUser`.
FYI, I'm using observing_squad mode.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bogdan-rosianu** [comment]
Hello. PR #5512 introduced support for historical vm queries. It will become available starting with the rc/v1.60 Polaris release

**Comment by sylviahuang123** [comment]
Thanks, but I tried on official devnet api, there was no difference with blockNonce changes
```
curl --location 'https://devnet-gateway.multiversx.com/vm-values/query?blockNonce=7909882' \
--header 'Content-Type: application/json' \
--data '{
  "scAddress": "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqx0llllsdx93z0",
  "funcName": "getTotalCumulatedRewardsForUser",
  "args": ["c2901f2531bb07a4aed96736ac06558d29602c1b577132a95a62a9c2467b9ad1"]
}'
```

**Comment by bogdan-rosianu** [comment]
Devnet doesn't have rc/v1.6.0 support. It will simply ignore the blockNonce property

**Comment by sylviahuang123** [comment]
Thank you, another question, devnet and mainnet, respectively, how long does it take to waiting to active and generate rewards after staking into legacy-delegation?

**Comment by bogdan-rosianu** [comment]
> Thank you, another question, devnet and mainnet, respectively, how long does it take to waiting to active and generate rewards after staking into legacy-delegation?

This was handled in #5619 :raised_hands:

**Comment by sylviahuang123** [comment]
> Devnet doesn't have rc/v1.6.0 support. It will simply ignore the blockNonce property

But I tried on mainnet `https://gateway.multiversx.com/vm-values/query?blockHash= ` still won't change, is it not on-line yet?

**Comment by sylviahuang123** [comment]
hello @bogdan-rosianu ?

**Comment by sylviahuang123** [comment]
is there any plan when active on mainnet?

**Comment by bogdan-rosianu** [comment]
It should arrive in the next release which is currently in the testing phase
