### ISSUE TITLE
[Question]: How long can I see the legacy-delegation's rewards?

### ISSUE THREAD

**Issue by sylviahuang123** [multiversx/mx-chain-go#5619]
### Please write the desired question

I have delegated to legacy-delegation for more than 10 days in devnet, but I found it is still in waiting-list, and no rewards, I want to know when I can see the reward, and which rpc I can query this? Thx.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bogdan-rosianu** [comment]
Hello! 

The Legacy Delegation has a threshold for a maximum number of tokens delegated (a delegation cap). If that number is reached, then all new delegation will go into waiting list, without a pre-defined time to wait before becoming eligible for rewards. 
I guess you are confusing the 10-day unbond period when unstaking with the waiting list of legacy delegation. They are not the same thing. Your delegated tokens will become eligible for rewards only if: 1) other users unstake their active funds so there will be more room for active tokens or 2) the contract owner will increase the delegation cap
