### ISSUE TITLE
[Question]: How to modify networkComponentsFactory create failed: no transports defined? pls

### ISSUE THREAD

**Issue by coinbase-op** [multiversx/mx-chain-go#5737]
### Please write the desired question

cmd:
`node --log-save --log-level=*:DEBUG,core/dblookupext:WARN --log-logger-name --destination-shard-as-observer=$SHARD --validator-key-pem-file=/egld/keys/validatorKey.pem --rest-api-interface=0.0.0.0:8080`

log:
```

INFO [2023-11-25 05:00:15.968] [factory]             p2p private key: generated a new private key for p2p signing
DEBUG[2023-11-25 05:00:15.968] [factory]             block sign pubkey                        value = b4f6d761593ba65535418daceacac87670de0d91a99f5729464dbad7d59c3d2a089c9cefa949c4b846d932d4d179af0d47f10cab07574221f5557950b6ebae2824406e67e51f872a96f9353db6ff98861dd6fe294966ad3f5dd03bc6125bd00a
DEBUG[2023-11-25 05:00:15.968] [node]                creating network components
DEBUG[2023-11-25 05:00:15.968] [p2p/libp2p]          generating random free port              range = 37373-38383
DEBUG[2023-11-25 05:00:15.970] [p2p/libp2p]          free port chosen                         port = 37763
DEBUG[2023-11-25 05:00:15.970] [p2p/libp2p]          connectionWatcherType                    type = disabled
ERROR[2023-11-25 05:00:15.970] [main]                networkComponentsFactory create failed: no transports defined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sstanculeanu** [comment]
Hello,

This error suggests that your `p2p.toml` config file does not have any transport defined, so make sure you have the proper configs version. The default config has TCP predefined.

Here is the config section that seems to be missing: 
- [mainnet](https://github.com/multiversx/mx-chain-mainnet-config/blob/master/p2p.toml#L19)
- [testnet](https://github.com/multiversx/mx-chain-testnet-config/blob/master/p2p.toml#L19)

**Comment by AdoAdoAdo** [comment]
no more questions, closing this issue.
