### ISSUE TITLE
[Bug]: Unable to locate this transaction hash

### ISSUE THREAD

**Issue by alfredogallo** [multiversx/mx-chain-go#5869]
### Contact Details

galloalfredo9111@gmail.com

### Description

during the collection of rewards on the hatom protocol but the transaction remains pending for the week, in the multiversx blockchain it is successful Unable to locate this transaction hash

### Steps to reproduce

During the collection of rewards on the hatom protocol but the transaction remains pending for the week, in the multiversx blockchain it is successful Unable to locate this transaction hash

### On which network is the bug manifesting itself?

Mainnet

### Relevant log output

```sh
2839b56aae833ded09ab4c0e3cfaa250e5c8976168834f96e745fa5724df5f34

transaction hash
```

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by AdoAdoAdo** [comment]
Can you give more details on this txhash?
e.g Which account was the sender of the corresponding tx.?

The tx may not exist on the chain if the transaction was not executed -  this can have multiple reasons higher nonce than the account nonce and exceed the time limit for staying in txpool, account guardian not matching the transaction guardian, etc.

**Comment by AdoAdoAdo** [comment]
Closing for now as no extra feedback.
